import logging
from typing import Dict, List, Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def escape_latex(text: str) -> str:
    if text is None:
        return ""
    
    replacements = {
        '\\': r'\textbackslash{}',
        '{': r'\{',
        '}': r'\}',
        '$': r'\$',
        '&': r'\&',
        '%': r'\%',
        '#': r'\#',
        '_': r'\_',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    
    result = str(text)
    for char, replacement in replacements.items():
        result = result.replace(char, replacement)
    
    return result


def generate_latex_header(filename: str) -> str:
    header = r'''\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{tikz}

\geometry{margin=1in}
\pagestyle{fancy}
\fancyhf{}
\rhead{PaperIQ Analysis Report}
\lhead{''' + escape_latex(filename) + r'''}
\cfoot{\thepage}

\definecolor{primaryblue}{RGB}{30,58,138}
\definecolor{lightblue}{RGB}{239,246,255}

\title{\textbf{PaperIQ Analysis Report}}
\author{Generated by PaperIQ}
\date{\today}

\begin{document}

\maketitle
\thispagestyle{empty}

'''
    return header


def generate_latex_footer() -> str:
    return r'\end{document}'


def generate_overview_section(data: Dict, filename: str) -> str:
    scores = data.get('scores', {})
    composite = scores.get('Composite', 0)
    domain = data.get('domain', 'N/A')
    
    section = r'\section{Overview}' + '\n\n'
    section += r'\begin{itemize}' + '\n'
    section += r'  \item \textbf{Document:} ' + escape_latex(filename) + '\n'
    section += r'  \item \textbf{Composite Score:} ' + f'{composite:.1f}/100' + '\n'
    section += r'  \item \textbf{Domain:} ' + escape_latex(domain) + '\n'
    section += r'\end{itemize}' + '\n\n'
    
    return section


def generate_scores_table(scores: Dict) -> str:
    section = r'\section{Metric Scores}' + '\n\n'
    section += r'\begin{table}[h]' + '\n'
    section += r'\centering' + '\n'
    section += r'\begin{tabular}{lc}' + '\n'
    section += r'\toprule' + '\n'
    section += r'\textbf{Metric} & \textbf{Score (0-100)} \\' + '\n'
    section += r'\midrule' + '\n'
    
    for metric, value in scores.items():
        if metric != 'Composite':
            section += escape_latex(metric) + f' & {value:.1f} \\\\\n'
    
    section += r'\midrule' + '\n'
    composite = scores.get('Composite', 0)
    section += r'\textbf{Composite} & \textbf{' + f'{composite:.1f}' + r'} \\' + '\n'
    section += r'\bottomrule' + '\n'
    section += r'\end{tabular}' + '\n'
    section += r'\caption{Analysis Metric Scores}' + '\n'
    section += r'\end{table}' + '\n\n'
    
    return section


def generate_statistics_section(stats: Dict) -> str:
    section = r'\section{Document Statistics}' + '\n\n'
    section += r'\begin{table}[h]' + '\n'
    section += r'\centering' + '\n'
    section += r'\begin{tabular}{lr}' + '\n'
    section += r'\toprule' + '\n'
    section += r'\textbf{Statistic} & \textbf{Value} \\' + '\n'
    section += r'\midrule' + '\n'
    
    stat_items = [
        ('Word Count', stats.get('word_count', 0)),
        ('Sentence Count', stats.get('sentence_count', 0)),
        ('Avg Sentence Length', f"{stats.get('avg_sentence_len', 0):.1f} words"),
        ('Avg Word Length', f"{stats.get('avg_word_len', 0):.1f} chars"),
        ('Total Citations', stats.get('total_citations', 0)),
        ('Citation Density', f"{stats.get('citation_density_per_1k', 0):.2f} per 1k"),
        ('Type-Token Ratio', f"{stats.get('type_token_ratio', 0):.4f}"),
        ('Complex Word Ratio', f"{stats.get('complex_word_ratio', 0):.2%}"),
    ]
    
    for label, value in stat_items:
        section += escape_latex(label) + ' & ' + escape_latex(str(value)) + r' \\' + '\n'
    
    section += r'\bottomrule' + '\n'
    section += r'\end{tabular}' + '\n'
    section += r'\caption{Document Statistics}' + '\n'
    section += r'\end{table}' + '\n\n'
    
    return section


def generate_keywords_section(keywords: List) -> str:
    if not keywords:
        return ''
    
    section = r'\section{Top Keywords}' + '\n\n'
    section += r'\begin{itemize}' + '\n'
    
    for kw, score in keywords[:15]:
        section += r'  \item ' + escape_latex(kw) + f' (score: {score:.4f})' + '\n'
    
    section += r'\end{itemize}' + '\n\n'
    
    return section


def generate_summary_section(summary: str) -> str:
    if not summary:
        return ''
    
    section = r'\section{Document Summary}' + '\n\n'
    section += escape_latex(summary) + '\n\n'
    
    return section


def generate_section_analysis(section_scores: List[Dict]) -> str:
    if not section_scores:
        return ''
    
    section = r'\section{Section-wise Analysis}' + '\n\n'
    section += r'\begin{table}[h]' + '\n'
    section += r'\centering' + '\n'
    section += r'\small' + '\n'
    section += r'\begin{tabular}{lcccc}' + '\n'
    section += r'\toprule' + '\n'
    section += r'\textbf{Section} & \textbf{Score} & \textbf{Words} & \textbf{Clarity} & \textbf{Readability} \\' + '\n'
    section += r'\midrule' + '\n'
    
    for sec in section_scores:
        sec_name = sec.get('section', 'Unknown')[:30]
        sec_score = sec.get('score', 0)
        sec_words = sec.get('word_count', 0)
        sec_clarity = sec.get('clarity_score', 0)
        sec_readability = sec.get('readability', 0)
        
        section += escape_latex(sec_name) + f' & {sec_score:.1f} & {sec_words} & {sec_clarity:.1f} & {sec_readability:.1f} \\\\\n'
    
    section += r'\bottomrule' + '\n'
    section += r'\end{tabular}' + '\n'
    section += r'\caption{Section-wise Quality Scores}' + '\n'
    section += r'\end{table}' + '\n\n'
    
    return section


def generate_structure_section(data: Dict) -> str:
    found = data.get('structural_found', [])
    missing = data.get('structural_missing', [])
    
    section = r'\section{Structural Analysis}' + '\n\n'
    
    if found:
        section += r'\subsection*{Detected Sections}' + '\n'
        section += r'\begin{itemize}' + '\n'
        for item in found:
            section += r'  \item ' + escape_latex(item) + '\n'
        section += r'\end{itemize}' + '\n\n'
    
    if missing:
        section += r'\subsection*{Missing Sections}' + '\n'
        section += r'\textcolor{red}{' + '\n'
        section += r'\begin{itemize}' + '\n'
        for item in missing:
            section += r'  \item ' + escape_latex(item) + '\n'
        section += r'\end{itemize}' + '\n'
        section += r'}' + '\n\n'
    
    sentiment = data.get('sentiment', 0)
    section += r'\subsection*{Sentiment Analysis}' + '\n'
    section += f'Sentiment Polarity: {sentiment:.2f} '
    
    if sentiment > 0.1:
        section += '(Positive)\n\n'
    elif sentiment < -0.1:
        section += '(Negative)\n\n'
    else:
        section += '(Neutral)\n\n'
    
    return section


def generate_advanced_analysis_section(advanced: Dict) -> str:
    if not advanced:
        return ''
    
    section = r'\section{Advanced Analysis}' + '\n\n'
    
    quality = advanced.get('quality_prediction', {})
    if quality:
        section += r'\subsection{Quality Assessment}' + '\n'
        section += r'\begin{itemize}' + '\n'
        section += r'  \item \textbf{Quality Score:} ' + f"{quality.get('quality_score', 0):.1f}/100" + '\n'
        section += r'  \item \textbf{Grade:} ' + escape_latex(quality.get('grade', 'N/A')) + '\n'
        section += r'  \item \textbf{Percentile:} ' + f"{quality.get('percentile_estimate', 0)}th" + '\n'
        section += r'\end{itemize}' + '\n\n'
        
        strengths = quality.get('strengths', [])
        if strengths:
            section += r'\textbf{Strengths:}' + '\n'
            section += r'\begin{itemize}' + '\n'
            for s in strengths[:5]:
                section += r'  \item ' + escape_latex(s) + '\n'
            section += r'\end{itemize}' + '\n\n'
        
        weaknesses = quality.get('weaknesses', [])
        if weaknesses:
            section += r'\textbf{Areas for Improvement:}' + '\n'
            section += r'\begin{itemize}' + '\n'
            for w in weaknesses[:5]:
                section += r'  \item ' + escape_latex(w) + '\n'
            section += r'\end{itemize}' + '\n\n'
    
    reproducibility = advanced.get('reproducibility', {})
    if reproducibility:
        section += r'\subsection{Reproducibility}' + '\n'
        rep_score = reproducibility.get('score', 0)
        rep_grade = reproducibility.get('grade', 'N/A')
        section += f'Score: {rep_score}/100 (Grade: {rep_grade})' + '\n\n'
    
    return section


def create_latex_export(data: Dict, filename: str, section_scores: List[Dict] = None) -> bytes:
    try:
        latex_content = generate_latex_header(filename)
        
        latex_content += generate_overview_section(data, filename)
        
        latex_content += generate_scores_table(data.get('scores', {}))
        
        latex_content += generate_statistics_section(data.get('stats', {}))
        
        keywords = data.get('keywords', [])
        if keywords:
            latex_content += generate_keywords_section(keywords)
        
        summary = data.get('document_summary', '')
        if summary:
            latex_content += generate_summary_section(summary)
        
        if section_scores:
            latex_content += generate_section_analysis(section_scores)
        
        latex_content += generate_structure_section(data)
        
        advanced = data.get('advanced', {})
        if advanced:
            latex_content += generate_advanced_analysis_section(advanced)
        
        latex_content += generate_latex_footer()
        
        return latex_content.encode('utf-8')
        
    except Exception as e:
        logger.error(f"Error generating LaTeX export: {e}")
        return b''
